"""Language data constants — single source of truth for all language-related lookups."""

LANGUAGE_FLAGS: dict[str, str] = {
    "af": "🇿🇦",
    "ar": "🇸🇦",
    "az": "🇦🇿",
    "be": "🇧🇾",
    "bg": "🇧🇬",
    "bn": "🇧🇩",
    "ca": "🇪🇸",
    "cs": "🇨🇿",
    "cy": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
    "da": "🇩🇰",
    "de": "🇩🇪",
    "el": "🇬🇷",
    "en": "🇬🇧",
    "eo": "🌍",
    "es": "🇪🇸",
    "et": "🇪🇪",
    "eu": "🇪🇸",
    "fa": "🇮🇷",
    "fi": "🇫🇮",
    "fil": "🇵🇭",
    "fr": "🇫🇷",
    "ga": "🇮🇪",
    "gl": "🇪🇸",
    "gu": "🇮🇳",
    "he": "🇮🇱",
    "hi": "🇮🇳",
    "hr": "🇭🇷",
    "hu": "🇭🇺",
    "hy": "🇦🇲",
    "id": "🇮🇩",
    "is": "🇮🇸",
    "it": "🇮🇹",
    "ja": "🇯🇵",
    "ka": "🇬🇪",
    "kk": "🇰🇿",
    "km": "🇰🇭",
    "ko": "🇰🇷",
    "ku": "🌍",
    "ky": "🇰🇬",
    "lt": "🇱🇹",
    "lv": "🇱🇻",
    "mk": "🇲🇰",
    "ml": "🇮🇳",
    "mn": "🇲🇳",
    "ms": "🇲🇾",
    "mt": "🇲🇹",
    "my": "🇲🇲",
    "nb": "🇳🇴",
    "ne": "🇳🇵",
    "nl": "🇳🇱",
    "no": "🇳🇴",
    "pa": "🇮🇳",
    "pl": "🇵🇱",
    "pt": "🇧🇷",
    "ro": "🇷🇴",
    "ru": "🇷🇺",
    "sk": "🇸🇰",
    "sl": "🇸🇮",
    "sq": "🇦🇱",
    "sr": "🇷🇸",
    "sv": "🇸🇪",
    "sw": "🇰🇪",
    "ta": "🇮🇳",
    "te": "🇮🇳",
    "th": "🇹🇭",
    "tl": "🇵🇭",
    "tr": "🇹🇷",
    "uk": "🇺🇦",
    "ur": "🇵🇰",
    "uz": "🇺🇿",
    "vi": "🇻🇳",
    "zh": "🇨🇳",
    "zu": "🇿🇦",
}

LANGUAGE_NAMES: dict[str, str] = {
    "af": "Afrikaans",
    "ar": "Arabic",
    "az": "Azerbaijani",
    "be": "Belarusian",
    "bg": "Bulgarian",
    "bn": "Bengali",
    "ca": "Catalan",
    "cs": "Czech",
    "cy": "Welsh",
    "da": "Danish",
    "de": "German",
    "el": "Greek",
    "en": "English",
    "eo": "Esperanto",
    "es": "Spanish",
    "et": "Estonian",
    "eu": "Basque",
    "fa": "Persian",
    "fi": "Finnish",
    "fil": "Filipino",
    "fr": "French",
    "ga": "Irish",
    "gl": "Galician",
    "gu": "Gujarati",
    "he": "Hebrew",
    "hi": "Hindi",
    "hr": "Croatian",
    "hu": "Hungarian",
    "hy": "Armenian",
    "id": "Indonesian",
    "is": "Icelandic",
    "it": "Italian",
    "ja": "Japanese",
    "ka": "Georgian",
    "kk": "Kazakh",
    "km": "Khmer",
    "ko": "Korean",
    "ku": "Kurdish",
    "ky": "Kyrgyz",
    "lt": "Lithuanian",
    "lv": "Latvian",
    "mk": "Macedonian",
    "ml": "Malayalam",
    "mn": "Mongolian",
    "ms": "Malay",
    "mt": "Maltese",
    "my": "Burmese",
    "nb": "Norwegian Bokmål",
    "ne": "Nepali",
    "nl": "Dutch",
    "no": "Norwegian",
    "pa": "Punjabi",
    "pl": "Polish",
    "pt": "Portuguese",
    "ro": "Romanian",
    "ru": "Russian",
    "sk": "Slovak",
    "sl": "Slovenian",
    "sq": "Albanian",
    "sr": "Serbian",
    "sv": "Swedish",
    "sw": "Swahili",
    "ta": "Tamil",
    "te": "Telugu",
    "th": "Thai",
    "tl": "Tagalog",
    "tr": "Turkish",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "uz": "Uzbek",
    "vi": "Vietnamese",
    "zh": "Chinese",
    "zu": "Zulu",
}

DEFAULT_QUESTION_COUNT: int = 3
DEFAULT_EPISODE_DURATION_MIN: int = 3
EPISODE_DURATION_OPTIONS: list[int] = [3, 5, 7, 10]

POOL_THRESHOLD: int = 16  # Refill when pool drops below this
POOL_FILL_SIZE: int = 30  # Cards to generate per LLM batch
POOL_RECENT_HINT: int = 20  # Words passed as soft exclusion hint in LLM prompt
