from enum import StrEnum


class Level(StrEnum):
    A1 = "A1"
    A2 = "A2"
    B1 = "B1"
    B2 = "B2"
    C1 = "C1"


class Goal(StrEnum):
    TRAVEL = "travel"
    WORK = "work"
    CONVERSATION = "conversation"
    GENERAL = "general"
    STUDY = "study"


class WordType(StrEnum):
    NOUN = "noun"
    VERB = "verb"
    ADJECTIVE = "adjective"
    PHRASE = "phrase"


class Language(StrEnum):
    AF = "af"
    AR = "ar"
    AZ = "az"
    BE = "be"
    BG = "bg"
    BN = "bn"
    CA = "ca"
    CS = "cs"
    CY = "cy"
    DA = "da"
    DE = "de"
    EL = "el"
    EN = "en"
    EO = "eo"
    ES = "es"
    ET = "et"
    EU = "eu"
    FA = "fa"
    FIL = "fil"
    FI = "fi"
    FR = "fr"
    GA = "ga"
    GL = "gl"
    GU = "gu"
    HE = "he"
    HI = "hi"
    HR = "hr"
    HU = "hu"
    HY = "hy"
    ID = "id"
    IS = "is"
    IT = "it"
    JA = "ja"
    KA = "ka"
    KK = "kk"
    KM = "km"
    KO = "ko"
    KU = "ku"
    KY = "ky"
    LT = "lt"
    LV = "lv"
    MK = "mk"
    ML = "ml"
    MN = "mn"
    MS = "ms"
    MT = "mt"
    MY = "my"
    NB = "nb"
    NE = "ne"
    NL = "nl"
    NO = "no"
    PA = "pa"
    PL = "pl"
    PT = "pt"
    RO = "ro"
    RU = "ru"
    SK = "sk"
    SL = "sl"
    SQ = "sq"
    SR = "sr"
    SV = "sv"
    SW = "sw"
    TA = "ta"
    TE = "te"
    TH = "th"
    TL = "tl"
    TR = "tr"
    UK = "uk"
    UR = "ur"
    UZ = "uz"
    VI = "vi"
    ZH = "zh"
    ZU = "zu"


class ActivityType(StrEnum):
    READING = "reading"
    WRITING = "writing"
    LISTENING = "listening"
    VOCAB = "vocab"


class MessengerType(StrEnum):
    TELEGRAM = "telegram"
