"""listening_model_index_added

Revision ID: 125401c24435
Revises: 1d2bbcb219bb
Create Date: 2026-04-14 14:52:17.973528

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "125401c24435"
down_revision: str | Sequence[str] | None = "1d2bbcb219bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_listening_history_user_episode", "listening_history", ["user_id", "episode_url"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_listening_history_user_episode", "listening_history", type_="unique")
    # ### end Alembic commands ###
