"""added_listel_history_model

Revision ID: 1d2bbcb219bb
Revises: 84f0cafe50c0
Create Date: 2026-04-13 21:56:12.070659

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d2bbcb219bb"
down_revision: str | Sequence[str] | None = "84f0cafe50c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "listening_history",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("target_lang", sa.Text(), nullable=False),
        sa.Column("episode_url", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_listening_history_user_id"), "listening_history", ["user_id"], unique=False
    )
    op.create_index(
        "ix_listening_history_user_lang",
        "listening_history",
        ["user_id", "target_lang"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_listening_history_user_lang", table_name="listening_history")
    op.drop_index(op.f("ix_listening_history_user_id"), table_name="listening_history")
    op.drop_table("listening_history")
    # ### end Alembic commands ###
