"""initial

Revision ID: 2361ec75771d
Revises:
Create Date: 2026-04-10 21:23:35.189814

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2361ec75771d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.Text(), nullable=True),
        sa.Column("level", sa.Text(), nullable=False),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column("native_lang", sa.Text(), nullable=False),
        sa.Column("session_minutes", sa.Integer(), nullable=False),
        sa.Column("target_lang", sa.Text(), server_default="de", nullable=False),
        sa.Column("reminder_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("reminder_time", sa.Text(), server_default="11:00", nullable=False),
        sa.Column("utc_offset", sa.Integer(), server_default="0", nullable=False),
        sa.Column("vocab_card_count", sa.Integer(), server_default="8", nullable=False),
        sa.Column(
            "decks", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("active_deck_id", sa.Text(), server_default="", nullable=False),
        sa.Column("vocab_scheduler_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("vocab_scheduler_time", sa.Text(), server_default="09:00", nullable=False),
        sa.Column("vocab_scheduler_deck_id", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "learning_strategy",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='["reading","writing","listening","vocab"]',
            nullable=False,
        ),
        sa.Column("question_count", sa.Integer(), server_default="3", nullable=False),
        sa.Column("episode_duration_min", sa.Integer(), server_default="3", nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id"),
    )
    op.create_table(
        "sessions",
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("article_url", sa.Text(), nullable=False),
        sa.Column("article_title", sa.Text(), nullable=False),
        sa.Column("article_text", sa.Text(), nullable=False),
        sa.Column(
            "questions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "user_answers",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("feedback", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "cards_created",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("duration_seconds", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_table(
        "vocab_history",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("target_lang", sa.Text(), nullable=False),
        sa.Column("word", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vocab_history_user_id"), "vocab_history", ["user_id"], unique=False)
    op.create_index(
        "ix_vocab_history_user_lang", "vocab_history", ["user_id", "target_lang"], unique=False
    )
    op.create_table(
        "vocab_pool",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("target_lang", sa.Text(), nullable=False),
        sa.Column("word", sa.Text(), nullable=False),
        sa.Column("translation", sa.Text(), nullable=False),
        sa.Column("example_sentence", sa.Text(), nullable=False),
        sa.Column("word_type", sa.Text(), nullable=False),
        sa.Column("article", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vocab_pool_user_id"), "vocab_pool", ["user_id"], unique=False)
    op.create_index(
        "ix_vocab_pool_user_lang", "vocab_pool", ["user_id", "target_lang"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_vocab_pool_user_lang", table_name="vocab_pool")
    op.drop_index(op.f("ix_vocab_pool_user_id"), table_name="vocab_pool")
    op.drop_table("vocab_pool")
    op.drop_index("ix_vocab_history_user_lang", table_name="vocab_history")
    op.drop_index(op.f("ix_vocab_history_user_id"), table_name="vocab_history")
    op.drop_table("vocab_history")
    op.drop_table("sessions")
    op.drop_table("profiles")
    # ### end Alembic commands ###
