"""listening_and_article_pools

Revision ID: 46c78ee8687d
Revises: 2c133629059c
Create Date: 2026-04-13 12:59:48.357947

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46c78ee8687d"
down_revision: str | Sequence[str] | None = "2c133629059c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "profiles",
        "messenger_type",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=False,
        existing_server_default=sa.text("'telegram'::character varying"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "profiles",
        "messenger_type",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        existing_server_default=sa.text("'telegram'::character varying"),
    )
    # ### end Alembic commands ###
