"""drop session_minutes

Revision ID: 619744d0ec7b
Revises: b2c3d4e5f6a7
Create Date: 2026-04-11 12:20:12.256226

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "619744d0ec7b"
down_revision: str | Sequence[str] | None = "b2c3d4e5f6a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "session_minutes")
    op.drop_index(op.f("ix_session_history_user"), table_name="session_history")
    op.create_index(
        op.f("ix_session_history_user_id"), "session_history", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_session_history_user_id"), table_name="session_history")
    op.create_index(op.f("ix_session_history_user"), "session_history", ["user_id"], unique=False)
    op.add_column(
        "profiles", sa.Column("session_minutes", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
