"""initial

Revision ID: 67719c0c10a4
Revises:
Create Date: 2026-04-05 20:41:19.119140

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67719c0c10a4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.Text(), nullable=True),
        sa.Column("level", sa.Text(), nullable=False),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column("native_lang", sa.Text(), nullable=False),
        sa.Column("session_minutes", sa.Integer(), nullable=False),
        sa.Column("target_lang", sa.Text(), server_default="de", nullable=False),
        sa.Column("reminder_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("reminder_time", sa.Text(), server_default="11:00", nullable=False),
        sa.Column("utc_offset", sa.Integer(), server_default="0", nullable=False),
        sa.Column("vocab_card_count", sa.Integer(), server_default="8", nullable=False),
        sa.Column(
            "decks", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("active_deck_id", sa.Text(), server_default="", nullable=False),
        sa.Column("vocab_scheduler_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("vocab_scheduler_time", sa.Text(), server_default="09:00", nullable=False),
        sa.Column("vocab_scheduler_deck_id", sa.Text(), server_default="", nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id"),
    )
    op.create_table(
        "sessions",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("article_url", sa.Text(), nullable=False),
        sa.Column("article_title", sa.Text(), nullable=False),
        sa.Column("article_text", sa.Text(), nullable=False),
        sa.Column(
            "questions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "user_answers",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("feedback", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "cards_created",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("duration_seconds", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sessions")
    op.drop_table("profiles")
    # ### end Alembic commands ###
