"""create_article_and_listening_pools

Revision ID: 84f0cafe50c0
Revises: 46c78ee8687d
Create Date: 2026-04-13 13:15:40.629635

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "84f0cafe50c0"
down_revision: str | Sequence[str] | None = "46c78ee8687d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "article_pool",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("target_lang", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "questions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_article_pool_user_id"), "article_pool", ["user_id"], unique=False)
    op.create_index(
        "ix_article_pool_user_lang", "article_pool", ["user_id", "target_lang"], unique=False
    )
    op.create_table(
        "listening_pool",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("target_lang", sa.Text(), nullable=False),
        sa.Column("episode_url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("transcript", sa.Text(), nullable=False),
        sa.Column(
            "questions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("level", sa.Text(), server_default="B1", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_listening_pool_user_id"), "listening_pool", ["user_id"], unique=False)
    op.create_index(
        "ix_listening_pool_user_lang", "listening_pool", ["user_id", "target_lang"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_listening_pool_user_lang", table_name="listening_pool")
    op.drop_index(op.f("ix_listening_pool_user_id"), table_name="listening_pool")
    op.drop_table("listening_pool")
    op.drop_index("ix_article_pool_user_lang", table_name="article_pool")
    op.drop_index(op.f("ix_article_pool_user_id"), table_name="article_pool")
    op.drop_table("article_pool")
    # ### end Alembic commands ###
