"""identity_table_added

Revision ID: ecddc5352de4
Revises: 125401c24435
Create Date: 2026-04-17 08:00:44.355434

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ecddc5352de4"
down_revision: str | Sequence[str] | None = "125401c24435"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "identities",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.Text(), nullable=False),
        sa.Column("platform_user_id", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_identities_user_id"), "identities", ["user_id"], unique=False)
    op.add_column(
        "profiles", sa.Column("next_reminder_at", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    op.drop_constraint(op.f("profiles_telegram_id_key"), "profiles", type_="unique")
    op.drop_column("profiles", "messenger_id")
    op.drop_column("profiles", "messenger_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles",
        sa.Column(
            "messenger_type",
            sa.TEXT(),
            server_default=sa.text("'telegram'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "profiles", sa.Column("messenger_id", sa.BIGINT(), autoincrement=False, nullable=False)
    )
    op.create_unique_constraint(
        op.f("profiles_telegram_id_key"),
        "profiles",
        ["messenger_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("profiles", "next_reminder_at")
    op.drop_index(op.f("ix_identities_user_id"), table_name="identities")
    op.drop_table("identities")
    # ### end Alembic commands ###
